---
title: "Boxplot With Points And Lines Using Ggplot2 Package"
author: Davit Sargsyan
date: 08/12/2017
output: 
  html_notebook:
    toc: true
---

### References
1. [**Bioconductor Support:** *Question: Inputting counts of zero into DESeq2*](https://support.bioconductor.org/p/63229/)

### Data
Create a dataset with 1000 gene counts (rows) in 100 samples (columns)

```{r Data, echo=TRUE, fig.height=5, fig.width=5, message=FALSE, warning=FALSE}
# Load packages----
# source("https://bioconductor.org/biocLite.R")
# biocLite("DESeq2")

require(data.table)
require(DESeq2)
require(BiocParallel)
require(glmmADMB)

set.seed(1000)

# Function: geometric means, disregard zeros----
gm_mean <- function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

# Sample grouping labels by treatment and timepoints----
n.trt <- 2
n.time <- 5
n.repl <- 10
n.sample <- n.trt*n.time*n.repl

grp <- data.table(sample = paste("Sample",
                                 1:(n.trt*n.time*n.repl)),
                  trt = factor(rep(rep(paste("Trt",
                                             LETTERS[1:(n.trt)],
                                             sep = ""), 
                                       each = n.repl),
                                   n.time)),
                  time = factor(rep(paste("Time", 
                                          1:n.time,
                                          sep = ""), 
                                    each = n.repl*n.trt)),
                  repl = factor(rep(paste("Replica",
                                          1:n.repl,
                                          sep = ""),
                                    n.trt*n.time),
                                levels = paste("Replica",
                                               1:n.repl,
                                               sep = "")))
grp

# Simulate data: assume increased counts in Treatment B,
# as well as increase over time
b0 <- 500
b1.trt <- 2*b0
b2.time <- 2*b0
b3.int <- 1*b0

v.mu <- b0 + 
  b1.trt*(as.numeric(grp$trt) - 1) + 
  b2.time*(as.numeric(grp$time) - 1) +
  b3.int*(as.numeric(grp$trt) - 1)*(as.numeric(grp$time) - 1)

# Random negative binomial----
n.row <- 1000
dt1 <- list()
for (i in 1:n.sample) {
  dt1[[i]] <- rnbinom(n = n.row,
                      mu = v.mu[i], 
                      size = v.mu[i])
}
dt1 <- do.call("cbind",
               dt1)

# Inflate zero counts----
prob.zero <- 0.2
zeros <- matrix(sample(x = c(0, 1),
                       size = n.row*n.sample,
                       replace = TRUE,
                       prob = c(prob.zero, 
                                1 - prob.zero)),
                ncol = n.sample)
dt1 <- data.table(dt1*zeros)
rownames(dt1) <- paste("Gene", 
                       1:n.row, 
                       sep = "")
colnames(dt1) <- paste("Sample", 
                       1:n.sample,
                       sep = "")
invisible({
  rm(zeros)
  gc()
})

dt1

# Example: Counts at Time 1----
tmp <- data.table(y = do.call("c",
                              (dt1[, 1:(2*n.repl)])),
                  x = rep(1:2, each = n.repl*n.row))
plot(tmp$y ~ jitter(tmp$x),
     xlab = "Treatments",
     ylab = "Counts",
     main = "Count Differences at Time 1",
     xaxt = "none")
points(tmp$y[tmp$y == 0] ~ jitter(tmp$x[tmp$y == 0]),
       col = "red")
axis(side = 1,
     at = 1:2,
     labels = c("Treatment A",
                "Treatment B"))
```

### Differential expression analysis based on the Negative Binomial (a.k.a. Gamma-Poisson) distribution (R package *DESeq2*)

```{r DESeq2, echo=TRUE, fig.height=5, fig.width=10, message=FALSE, warning=FALSE}
# Bild a DESeq2 model with treatment*time interaction----
dds <- DESeqDataSetFromMatrix(dt1, 
                              grp,
                              ~ trt + time + trt:time)

# If all samples contain zeros, geometric means cannot be
# estimated. Change default 'type = "ratio"' to 'type = "iterate"'.
# Type '?DESeq2::estimateSizeFactors' for more details.
# dss <- estimateSizeFactors(dds, 
#                            type = "iterate")

#ALTERNATEVELY: exclude zeros from geometric mean calculation----
geoMeans <- apply(X = counts(dds), 
                  MARGIN = 1,
                  FUN = gm_mean)

dds <- estimateSizeFactors(object = dds,
                           geoMeans = geoMeans)

# Set cores for parallel processing of DESeq----
snowparam <- SnowParam(workers = snowWorkers(), 
                       type = "SOCK")
register(snowparam, 
         default = TRUE)

# Run DESeq----
dds <- DESeq(dds,
             fitType = "local",
             parallel = TRUE)
resultsNames(dds)

# Contrasts----
# a. Treatment B/Treatment A at Time 1----
resAvsBtime1 <- results(dds,
                        name = "trt_TrtB_vs_TrtA")

# b. Treatment B/Treatment A at Time 2----
resAvsBtime2 <- results(dds,
                        contrast = list(c("trt_TrtB_vs_TrtA" ,
                                          "trtTrtB.timeTime2")))

# ALTERNATIVE GROUPING----
# Create a mixed-level factor----
grp$trt_time <- factor(paste(grp$trt, 
                             grp$time,
                             sep = "_"))

dds.mix <- DESeqDataSetFromMatrix(dt1, 
                                  grp,
                                  ~ trt_time)

geoMeans.mix <- apply(X = counts(dds.mix), 
                      MARGIN = 1,
                      FUN = gm_mean)

dds.mix <- estimateSizeFactors(object = dds.mix,
                               geoMeans = geoMeans.mix)

# Run DESeq----
dds.mix <- DESeq(dds.mix,
                 fitType = "local",
                 parallel = TRUE)
resultsNames(dds.mix)

# Contrasts----
# a. Treatment B/Treatment A at Time 1----
resAvsBtime1.mix <- results(dds.mix,
                            contrast = c("trt_time",
                                         "TrtB_Time1",
                                         "TrtA_Time1"))
# Compare
data.table(do.call("cbind", 
                   resAvsBtime1@listData))
data.table(do.call("cbind", 
                   resAvsBtime1.mix@listData))

# b. Treatment B/Treatment A at Time 2----
resAvsBtime2.mix <- results(dds.mix,
                            contrast = c("trt_time",
                                         "TrtB_Time2",
                                         "TrtA_Time2"))
# Compare
data.table(do.call("cbind", 
                   resAvsBtime2@listData))
data.table(do.call("cbind", 
                   resAvsBtime2.mix@listData))
```


```{r glmmADMB, echo=TRUE, fig.height=5, fig.width=10, message=FALSE, warning=FALSE}
# Merge counts with grouping
dt.l <- data.table(grp, t(dt1))
colnames(dt.l)[5:ncol(dt.l)] <- rownames(dt1)

# Melt data table
dt.l <- melt.data.table(data = dt.l,
                        id.vars = colnames(grp),
                        measure.vars = 5:ncol(dt.l),
                        variable.name = "gene",
                        value.name = "count")

# Model
tmp <- droplevels(subset(dt.l,
              dt.l$gene == "Gene1"))

out <- list()
for (i in 1:nlevels(dt2.KO$otu)) {
  # Subset the data to i-th OTU
  tmp.i <- droplevels(subset(dt2.KO,
                             otu == levels(otu)[i]))
  
  # Try building the model
  res <- try({
    out[[i]] <- glmmadmb(Count ~ Treatment*Week + (Treatment | MouseID) + offset(sample.gmean),
                    family = "nbinom",
                    save.dir = "tmp/glmmadmb_out",
                    # zeroInflation = TRUE,
                    data = tmp.i)
  })
  if (class(res)[1] == "try-error") {          
    out[[i]] <- NA
  }
  print(paste("Processing OTU", i, "..."))
}
names(out) <- levels(dt2.KO$otu)
out
```